/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import negocio.BOReportes;
import objetos.objReportes;

/**
 *
 * @author Michelle
 */
public class Reporte2 extends javax.swing.JFrame {

    /**
     * Creates new form Reporte2
     */
    public Reporte2() {
        initComponents();
        setLocationRelativeTo(null);
        repaint();
    }
    BOReportes boreportes = new BOReportes();

    public void paint(Graphics g){
        int porcentaje1 = 0;
        int porcentaje2 = 0;
        int porcentaje3 = 0;
        super.paint(g);
        objReportes.listareportes= new ArrayList<>();
        ArrayList<objReportes> datosP = boreportes.cargarReporte2();  
        for(int i =0;i<datosP.size();i++){
            if(datosP.get(i).getNombre().equals("Planta 1"))
                porcentaje1 = datosP.get(i).getPorcentaje();
            else if(datosP.get(i).getNombre().equals("Planta 2")){
                porcentaje2 = datosP.get(i).getPorcentaje();
            }else if(datosP.get(i).getNombre().equals("Planta 3")){
                porcentaje3 = datosP.get(i).getPorcentaje();
            }
        }

        int total = porcentaje1 +porcentaje2+porcentaje3;
        
        int grados1 = porcentaje1*360/total;
        int grados2 = porcentaje2*360/total;
        int grados3 = porcentaje3*360/total;
        
        g.setColor(new Color(255,0,0));
        g.fillArc(25, 80, 200, 200, 0, grados1);
        g.fillRect(250, 120, 20, 20);
        g.drawString("Planta 1: "+porcentaje1+"%", 275, 135);
        
        g.setColor(new Color(0,130,0));
        g.fillArc(25, 80, 200, 200, grados1, grados2);
        g.fillRect(250, 150, 20, 20);
        g.drawString("Planta 2: "+porcentaje2+"%", 275, 165);
        
        g.setColor(new Color(0,0,255));
        g.fillArc(25, 80, 200, 200, grados1+grados2, grados3);
        g.fillRect(250, 180, 20, 20);
        g.drawString("Planta 3: "+porcentaje3+"%", 275, 195);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(367, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reporte2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reporte2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reporte2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reporte2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reporte2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
